#© 2021 Sean Murdock

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-stedi-matthew
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-stedi-matthew
  template:
    metadata:
      labels:
        app: prod-stedi-matthew
    spec:
      containers:
        - name: prod-stedi-matthew
          image: us-docker.pkg.dev/group3-iam-project/matthew-api/api-tests:latest # This image needs to refer 
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secrets-prod
                  key: REDIS_PASS
            - name: REDIS_HOST
              value: "redis-prod-stedi-matthew"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: KAFKA_BROKER
              value: "localhost:9092"
            - name: TWILIO_AUTH_TOKEN
              valueForm:
                secretKeyRef:
                  name: matthew-twilio-dev
                  key: twilio_token
          ports:
            - containerPort: 443
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 4567
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: prod-stedi-matthew-nodeport
spec:
  selector:
    app: prod-stedi-matthew
  type: NodePort
  ports:
    - port: 80
      targetPort: 4567
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prod-stedi-matthew-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: prod-stedi-matthew-public # not yet created before applying the yaml
    networking.gke.io/managed-certificates: prod-stedi-matthew-certificate
    # kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prod-stedi-matthew-nodeport # this needs to match line 53
            port:
              number: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: prod-stedi-matthew-certificate # this needs to match line 68
spec:
  domains:
    - matthew.cit262.com # this is a dns record that that has not been created
    
